# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWcN1W6GRh8U7MS5UcSAdzpQuGROOrMV
"""

!pip install pandas nltk scikit-learn matplotlib seaborn

import pandas as pd
import nltk
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('punkt')
nltk.download('stopwords')

"""**Loading the dataset**"""

df = pd.read_csv("IMDB Dataset.csv")
df.head()

df.info()
df['sentiment'].value_counts()

"""**Clean the Dataset**"""

df = df.dropna()
df['review'] = df['review'].astype(str)

"""**Create Positive & Negative Corpora**"""

positive_reviews = df[df['sentiment'] == 'positive']['review']
negative_reviews = df[df['sentiment'] == 'negative']['review']

print("Positive reviews:", len(positive_reviews))
print("Negative reviews:", len(negative_reviews))

"""**Text Preprocessing**"""

stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = text.lower()
    tokens = nltk.word_tokenize(text)
    tokens = [word for word in tokens if word.isalpha() and word not in stop_words]
    return " ".join(tokens)
positive_clean = positive_reviews.apply(preprocess_text)
negative_clean = negative_reviews.apply(preprocess_text)
positive_clean.head()

"""**TF-IDF Model Creation (Separate for Each Sentiment)**"""

tfidf_pos = TfidfVectorizer(max_features=5000)
tfidf_neg = TfidfVectorizer(max_features=5000)

tfidf_pos_matrix = tfidf_pos.fit_transform(positive_clean)
tfidf_neg_matrix = tfidf_neg.fit_transform(negative_clean)

def get_top_terms(tfidf_matrix, feature_names, top_n=15):
    avg_scores = np.mean(tfidf_matrix.toarray(), axis=0)
    top_indices = avg_scores.argsort()[::-1][:top_n]
    return [(feature_names[i], avg_scores[i]) for i in top_indices]
top_positive_terms = get_top_terms(
    tfidf_pos_matrix, tfidf_pos.get_feature_names_out()
)

top_negative_terms = get_top_terms(
    tfidf_neg_matrix, tfidf_neg.get_feature_names_out()
)

print("Top 15 TF-IDF Terms in Positive Reviews:\n")
for word, score in top_positive_terms:
    print(f"{word}: {score:.4f}")

print("\nTop 15 TF-IDF Terms in Negative Reviews:\n")
for word, score in top_negative_terms:
    print(f"{word}: {score:.4f}")

"""**Comparative visualization**"""

pos_words, pos_scores = zip(*top_positive_terms)
neg_words, neg_scores = zip(*top_negative_terms)
plt.figure(figsize=(14,6))
# Positive
plt.subplot(1,2,1)
sns.barplot(x=pos_scores, y=pos_words)
plt.title("Top 15 TF-IDF Terms – Positive Reviews")
plt.xlabel("TF-IDF Score")
# Negative
plt.subplot(1,2,2)
sns.barplot(x=neg_scores, y=neg_words)
plt.title("Top 15 TF-IDF Terms – Negative Reviews")
plt.xlabel("TF-IDF Score")
plt.tight_layout()
plt.show()